name: Deploy
on:
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: self-hosted
    environment: myvps

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: npm install

    - name: Set Environment Variables
      run: |
        echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" >> .env.local
        echo "YOUTUBE_CHANNEL_ID=${{ secrets.YOUTUBE_CHANNEL_ID }}" >> .env.local
        echo "GOOGLE_CALENDAR_ID=${{ secrets.GOOGLE_CALENDAR_ID }}" >> .env.local
        echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env.local
        echo "NEXT_PUBLIC_BASE_URL=${{ secrets.NEXT_PUBLIC_BASE_URL }}" >> .env.local
        echo "NODE_ENV=production" >> .env.local
        echo "API_SECRET_KEY=${{ secrets.API_SECRET_KEY }}" >> .env.local
      shell: bash

    - name: Build Application
      run: npm run build

    - name: Restart PM2 Server Process
      run: pm2 restart temploaa --silent
