name: Deploy
on:
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: self-hosted
    environment: myvps

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: npm install

    - name: Build App
      run: npm run build

    - name: Restart pm2 Server PRocess
      run: pm2 restart temploaa --silent
      shell: bash
