name: Deploy
on:
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: self-hosted
    environment: myvps

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: npm install

    - name: Build App
      run: npm run build

    - name: Set Environment Variables
      run: |
        echo "YOUTUBE_API_KEY=${{ secrets.YOUTUBE_API_KEY }}" >> .env.local
        echo "YOUTUBE_CHANNEL_ID=${{ secrets.YOUTUBE_CHANNEL_ID }}" >> .env.local
      shell: bash

    - name: Setup Cron Job
      run: |
        export YOUTUBE_API_KEY="${{ secrets.YOUTUBE_API_KEY }}"
        export YOUTUBE_CHANNEL_ID="${{ secrets.YOUTUBE_CHANNEL_ID }}"
        ./scripts/setup-cron.sh
      shell: bash

    - name: Restart pm2 Server Process
      run: pm2 restart temploaa --silent
      shell: bash
