name: Deploy
on:
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: self-hosted
    environment: myvps

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Install Client Dependencies
      working-directory: ./client
      run: npm install

    - name: Create Client env file
      working-directory: ./client
      run: |
        echo '{
          "NEXT_PUBLIC_API_KEY": "${{ secrets.NEXT_PUBLIC_API_KEY }}",
          "NEXT_PUBLIC_API_URL": "${{ secrets.NEXT_PUBLIC_API_URL }}",
        }' > .env.local
      shell: bash
    
    - name: Create Client Build
      working-directory: ./client
      run: npm run build
      shell: bash

    - name: Install API Dependencies
      working-directory: ./api
      run: npm install

    - name: Create API env file
      working-directory: ./api
      run: |
        echo '{
          "MONGODB_URI": "${{ secrets.MONGODB_URI }}",
          "API_SECRET_KEY": "${{ secrets.API_SECRET_KEY }}",
          "GOOGLE_API_KEY": "${{ secrets.GOOGLE_API_KEY }}",
          "YOUTUBE_CHANNEL_ID": "${{ secrets.YOUTUBE_CHANNEL_ID }}",
          "GOOGLE_CALENDAR_ID": "${{ secrets.GOOGLE_CALENDAR_ID }}",
          "PORT": "${{ secrets.PORT }}",
          "NODE_ENV": "production",
          "FRONTEND_URL": "${{ secrets.FRONTEND_URL }}",
        }' > .env.local
      shell: bash

    - name: Build API
      working-directory: ./api
      run: npm run build
      shell: bash

    - name: Restart PM2 Server Process
      run: pm2 restart temploaa --silent
      shell: bash
